name: Deploy Infrastructure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Initialize Terraform
        run: terraform init

      - name: Apply Terraform
        run: terraform apply -auto-approve

      - name: Build and push Docker images
        run: |
          docker build -t your-docker-repo/byte_architect ./byte_architect
          docker build -t your-docker-repo/configurator ./configurator
          docker push your-docker-repo/byte_architect
          docker push your-docker-repo/configurator

      - name: Deploy Docker Compose
        run: |
          docker-compose down
          docker-compose up -d
